# Changes here will be overwritten by Copier
SelectCodeQualityFeatures:
- AddLocalTests_flag
- SelectGitHubActions_flag
- AddLinting_flag
SelectCommunityFeatures:
- AddContributing_flag
SelectDocumentationFeatures:
- AddLocalDocumentation_flag
- AddOnlineDocumentation_flag
- AddDevDoc_flag
- AddGitHubActionDocumentation_flag
SelectGitHubActions:
- AddGitHubActionBuild_flag
- AddLinkCheck_flag
SelectPublishReleaseFeatures:
- AddChangeLog_flag
_commit: 0.6.1
_src_path: https://github.com/nlesc/python-template.git
copyright_holder: Helge Hecht
email: helge.hecht@recetox.muni.cz
full_name: Helge Hecht
github_organization: RECETOX
keywords: proteomics,dbsnp,amino-acid,polymorphism
license: MIT
package_name: freqsap
package_short_description: freqsap can be used to query the frequency of single amino-acid
    polymorphisms
template_profile: ask
version: 0.1.0
